### PR TITLE
Create allAgricultureColleges.json

### PR DESCRIPTION
**Pull request by Over-Thinker**
Added Some Famous Agriculture Colleges

## Description
Added Some Famous Agriculture Colleges  situated in Indian .

---
## Issue Ticket Number
Fixes #(issue_number)

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✓ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [ ✓] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [✓ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Clueless-Community/collegeAPI/pulls) for the same update/change?
- [ ✓] I have performed a self-review of my own code
- [ ✓] I have commented my code, particularly in hard-to-understand areas
- [✓ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey @Over-Thinker, Agriculture colleges are not listed in NIRF right?👀
What page did you scrap to get this data? Please mention here

**Comment by Over-Thinker** [comment]
No actually these colleges are not listed in basis of nirf.
I got those data from college dunia and also some other pages then i make a list of top ranked colleges and then put those . Here the serial is not in nirf ranked but the serial is also from top ranked college to button rank college you can check 😅.

**Comment by nikhil25803** [comment]
Hey @Over-Thinker, then it will be specific to the website only right? So we cannot merge this.

**Comment by Over-Thinker** [comment]
No actually it's not based only the website I also followed some some list also from nirf rank so pls review once

**Comment by nikhil25803** [comment]
Okay @Over-Thinker, please upload the respective python file too. That you used to scrape data.

**Comment by nikhil25803** [comment]
The files are still not uploaded yet @Over-Thinker

**Comment by Over-Thinker** [comment]
Now check please

**Comment by nikhil25803** [comment]
Hey @Over-Thinker , also define the endpoint in the `main.py` file. Set the endpoints as `agriculture_colleges`

**Comment by nikhil25803** [comment]
There are some merge conflicts, please resolve them first.

**Pull request closed without merging**
